name: Synchronisation des labels

on:
  push:
    branches: [main, develop]
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  labels:
    name: Créer / mettre à jour les labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
